# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  - repo: self

name: Kahn's Test Repo

stages:
  - stage: Compile_and_Test
    displayName: 'Compile and test code'
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Compile
        displayName: 'Compile'
        steps:
             
          - script: |
              sbt clean test
            displayName: 'Test'
            condition: succeededOrFailed()
 
          - script: |
              sbt assembly
            displayName: 'Assembly'
            condition: succeededOrFailed()

          - publish: '$(Build.SourcesDirectory)/target/scala-2.13/testRepo'
            displayName: 'Publish jars for later use'
            artifact: jars
 
 
