# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: Compile_and_Test
    displayName: 'Compile and test code'
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: Compile
        displayName: 'Compile'
        steps:
             
          - script: |
              sbt clean test
            displayName: 'Test'
            condition: succeededOrFailed()
 
          - script: |
              sbt assembly
            displayName: 'Assembly'
            condition: succeededOrFailed()

          - publish: '$(Build.ArtifactStagingDirectory)/appserver'
            displayName: 'Publish jars for later use'
            artifact: jars
 
 
